name: Install TeamViewer and Retrieve ID

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: macos-14 # Use macOS runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeamViewer
        run: |
          brew install --cask teamviewer
          echo "TeamViewer installed successfully."

      - name: Wait for TeamViewer to initialize
        run: |
          echo "Waiting for TeamViewer to initialize..."
          sleep 10 # Give some time for TeamViewer to register an ID

      - name: Check TeamViewer Installation
        run: |
          if ! command -v teamviewer &> /dev/null; then
            echo "TeamViewer installation failed!"
            exit 1
          fi
          echo "TeamViewer is installed."

      - name: Get TeamViewer ID
        run: |
          # Try to retrieve the TeamViewer ID
          TEAMVIEWER_ID=$(teamviewer info | grep "TeamViewer ID" | awk '{print $4}')
          
          if [[ -z "$TEAMVIEWER_ID" ]]; then
            echo "Failed to retrieve TeamViewer ID!"
            exit 1
          fi
          
          echo "TeamViewer ID: $TEAMVIEWER_ID"
          echo "TEAMVIEWER_ID=$TEAMVIEWER_ID" >> $GITHUB_ENV

      - name: Save TeamViewer ID to File
        run: |
          echo "$TEAMVIEWER_ID" > teamviewer_id.txt

      - name: Upload TeamViewer ID as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TeamViewer-ID
          path: teamviewer_id.txt
          if-no-files-found: error # Fail if file is missing
