name: macOS VNC Setup
on:
  workflow_dispatch:

jobs:
  setup-vnc:
    runs-on: macOS-14
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        # Install Homebrew if not exists
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "$(brew --prefix)/opt/openssl@3/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        brew update
        brew install perl
        brew install --cask ngrok

    - name: Make script executable
      run: chmod +x setup.sh

    - name: Run VNC Setup
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        PASSWD: ${{ secrets.VNC_PASSWORD }}
      run: |
        ./setup.sh "$PASSWD" "$PASSWD" "$NGROK_AUTH_TOKEN"

    - name: Get Ngrok URL
      run: |
        sleep 25  # Wait for ngrok to start
        echo "Ngrok URL: $(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"

    - name: Debug with tmate
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
