name: Mac Remote Access

on:  
  workflow_dispatch  # Manual trigger

jobs:
  remote-access:
    runs-on: macos-latest  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ngrok
        run: |
          brew install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start SSH Server
        run: |
          sudo systemsetup -setremotelogin on
          sudo dscl . -create /Users/github
          sudo dscl . -passwd /Users/github password123
          sudo dscl . -append /Groups/admin GroupMembership github
          sudo launchctl load /System/Library/LaunchDaemons/ssh.plist

      - name: Start Ngrok Tunnel
        run: |
          ngrok tcp 22 > ngrok.log &
          sleep 5
          curl -s http://localhost:4040/api/tunnels > tunnels.json
          echo "Ngrok SSH Tunnel:"
          cat tunnels.json | jq -r '.tunnels[0].public_url'

      - name: Keep Workflow Alive
        run: sleep 86400  # Keeps workflow running for 24 hours
